spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb
    username: appuser
    password: appsecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: picpay

api:
  authorization:
    url: https://util.devi.tools/api/v2/authorize