spring.application.name=picpay
server.servlet.context-path=/picpay-app

spring.datasource.url=jdbc:mysql://localhost:3306/picpay
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=pass123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect